version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/core
    ports:
      - 8000:8000
    image: app:docker_test_1
    container_name: docker_container
    command: python manage.py runserver 0.0.0.0:8000
